name: 'Miaow action'
on:
  pull_request:
    branches:
      - main
  issues:
    types: [opened, edited, reopened, labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  miaow:
    runs-on: ubuntu-latest
    concurrency:
      group: issue-${{ github.event.issue.number }} || pr-${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./
        id: app
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
