name: 'Miaow action'
on:
  pull_request:
    branches:
      - main
  issues:
    types: [opened, edited, reopened, labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  miaow:
    runs-on: ubuntu-latest
    concurrency:
      group: issue-${{ github.event.issue.number }} || pr-${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./
        id: app
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
